before_script:
  - apt-get update
  - echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
  - . ~/.bashrc
  - mkdir ~/local
  - mkdir ~/node-latest-install
  - cd ~/node-latest-install
  - curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
  - ./configure --prefix=~/local
  - make install 
  - curl https://www.npmjs.org/install.sh | sh
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g bower
  - mkdir ~/tmp
  - pushd ~/tmp
  - wget http://www.ime.usp.br/~kazuo/monitoria/phantomjs-1.9.7-linux-x86_64.tar.bz2
  - tar xf phantomjs-1.9.7-linux-x86_64.tar.bz2
  - mv phantomjs-1.9.7-linux-x86_64 phantomjs
  - ln -s ~/tmp/phantomjs/bin/phantomjs /usr/bin/phantomjs
  - phantomjs --version
  - popd
  - ls
  - cd projProfParticular/
  - bower install --allow-root
  
unit-tests:
  script:
    - ./run_tests.sh unit
    
e2e-tests:
  script:
    - ./run_tests.sh e2e