image: node:4.2.2

before_script:
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g bower
  - npm install karma --save-dev
  - npm install karma-jasmine --save-dev
  - npm install karma-phantomjs-launcher --save-dev
  - npm install -g karma-cli
  - npm install -g phantomjs
  - npm install selenium-webdriver
  - npm install -g protractor
  - webdriver-manager update
  - cd projProfParticular/
  - bower install --allow-root
  
unit-tests:
  script:
    - ./run_tests.sh unit
    
#e2e-tests:
# script:
#    - ./run_tests.sh e2e
