image: node:4.2.2

before_script:
  - apt-get update
  - cd /opt/
  - wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-linux-x64.tar.gz"
  - tar xzf jdk-8u66-linux-x64.tar.gz
  - rm jdk-8u66-linux-x64.tar.gz
  - java -version
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g bower
  - npm install karma --save-dev
  - npm install karma-jasmine --save-dev
  - npm install karma-phantomjs-launcher --save-dev
  - npm install -g karma-cli
  - npm install -g phantomjs
  - npm install -g protractor
  - webdriver-manager update
  - cd projProfParticular/
  - bower install --allow-root
  
unit-tests:
  script:
    - ./run_tests.sh unit
    
#e2e-tests:
#  script:
#    - ./run_tests.sh e2e
