image: node:4.2.2

before_script:
  - apt-get update
  - mkdir /opt/jdk
  - cd /opt
  - wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
  - tar -zxf jdk-8u5-linux-x64.tar.gz -C /opt/jdk
  - update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_05/bin/java 100
  - update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_05/bin/javac 100
  - java -version
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g bower
  - npm install karma --save-dev
  - npm install karma-jasmine --save-dev
  - npm install karma-phantomjs-launcher --save-dev
  - npm install -g karma-cli
  - npm install -g phantomjs
  - npm install -g protractor
  - webdriver-manager update
  - cd projProfParticular/
  - bower install --allow-root
  
unit-tests:
  script:
    - ./run_tests.sh unit
    
#e2e-tests:
#  script:
#    - ./run_tests.sh e2e
