image: node:4.2.2

before_script:
  - apt-get update
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - apt-get install google-chrome-stable
  - npm install -g cordova
  - npm install -g ionic
  - npm install -g bower
  - npm install karma --save-dev
  - npm install karma-jasmine --save-dev
  - npm install karma-phantomjs-launcher --save-dev
  - npm install -g karma-cli
  - npm install -g phantomjs
  - npm install -g protractor
  - webdriver-manager update
  - cd projProfParticular/
  - bower install --allow-root
  
unit-tests:
  script:
    - ./run_tests.sh unit
    
e2e-tests:
  script:
    - ./run_tests.sh e2e